services:
  - type: web
    name: dea-malela-portal
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:W7wsAxNuMf6bQO3YPS9637RDAL1HdC+KaMWFcfrmJUg=
      - key: APP_URL
        value: https://dea-malela-portal.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: dea-malela-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dea-malela-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dea-malela-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dea-malela-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dea-malela-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: dea-malela-db
    databaseName: dea_malela
    user: dea_malela_user
